### PR TITLE
testing lgtm pr things

### PR DESCRIPTION
**Pull request by eshansingh**
Testing LGTM

---
This change is [Reviewable](https://reviewable.io/reviews/cyclejs-community/cycle-ui-kit/15)

### CODE REVIEW

**Comment by GitCop** [comment]
Hey, something's not quite right with your PR:

 * Commit: 6a038e41381b2a46d1d70116f00849f095bc5074
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

You can fix these commit messages by using `git rebase`'s interactive mode. Even better, use `git cz` instead of `git commit` to commit according to the required style.

---
This message was auto-generated by https://gitcop.com

**Comment by eshansingh** [comment]
OK, gitcop works too.

**Comment by eshansingh** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cyclejs-community/cycle-ui-kit/15)*

**Comment by wyqydsyq** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cyclejs-community/cycle-ui-kit/15#-:-KOOJemu4gNSK9R5p5Ie:bnfp4nl)*

**Comment by eshansingh** [comment]
Seems like it works.

**Pull request closed without merging**
